# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || "rails_development" %>
  username: <%= ENV['DATABASE_USER'] || "postgres" %>
  password: <%= ENV['DATABASE_PASSWORD'] || "postgres" %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
